
CAN developing
==============

Contents
========

. <<starting-with-socketcan,Starting with SocketCAN>>

[[starting-with-socketcan]]Starting with socketcan
==================================================

The first things to do when starting to develop for CAN for HAL is to get
comfortable with the CAN interface. SocketCAN is native to Linux, and
we can use SocketCAN when developing so there is no need for hardware
or devices.

You should probably have a go at this link:http://www.can-cia.org/fileadmin/cia/files/icc/13/kleine-budde.pdf[document which describes socketcan]
to get a little background of what SocketCAN is. When we have used
SocketCAN then the real hardware works in the same way. Only difference will be
that we swap the driver to the real hardware.


. Install a Virtual Machine. The one used in these examples is Debian Jessie,
  but it could as well be. You can use VirtualBox, or other VM's. Choice is up
  to you. For these examples Parallels 9, on a Macbook Pro was used for the
  Debian Jessie VM.
. link:../setting-up/CAN-developing-setup.asciidoc[set up the environment so you can use socketcan]
  then return here.
. more to come
