---
layout: docs
---
:imagesoutdir: docs/site/about-this-site


== How to use this website

=== Search

This is a custom Google search engine covering the www.machinekit.io website and the http://blog.machinekit.io/[blog].

=== Editing pages

The site source is hosted on link:https://github.com/machinekit/machinekit-docs[github] - if you want to edit content,
you need to have a github account. Changing the website works like any other change to machinekit - using the normal http://www.machinekit.io/community/c4/[C4 process]: you create a Pull Request, which is merged by
one of the maintainers, after which the changes are incorporated into the source of machinekit, or - in this case - the website.

You will find that allmost all pages have an link:https://github.com/machinekit/machinekit-docs//edit/master/docs/site/about-this-site.asciidoc[Edit this page] link in the right column. Clicking link leads you directly into edit mode on github - after you have made your changes, describe what they are about in the 'Commit changes' box at the bottom, 'Create a new branch for this commit and start a pull request', then click
'Propose file change'

=== Previewing changes

Opening a Pull Request triggers an update of preview.machinekit.io and your change should be online within minutes. This process is capable of only showing the latest PR - but the status of the preview formatting run is recorded in the PR status.

=== Going live: merge by maintainers

As soon as a maintainer gets around to merge your PR, the result is rendered on www.machinekit.io. This step takes
slightly longer - but typically less than two minutes - as it runs a http://www.machinekit.io/linkchecker.html[linkchecker]
step to analyze the site for broken links.


