== Building a rt-preempt kernel for Debian Jessie - x86-amd64

There are currently no stock Debian rt-preempt kernels available for Debian Jessie

Building your own is not difficult providing you have a full development system installed.

The best way to approach this is to go to www.kernel.org/pub/linux/kernel/projects/rt/
and select the latest stable patch

Then download the matching vanilla kernel from www.kernel.org.

These sample instructions cover the building of kernel 3.8.11 with rt patch no 7

Substitute the kernel version you have for 3.8.11 and the rt patch version you have for 3.8.11-rt7 in the below instructions

All the recent rt x86-amd64 patches up to kernel 4.1.5 have been tested and all worked well.

Cut and Paste link:./rt-kernel-config[this] config to a file called .config in the root directory of the kernel sources.

=== Commands from a terminal
cd ~

mkdir rtlinux

cd rtlinux

wget -c ftp://ftp.kernel.org/pub/linux/kernel/v3.x/linux-3.18.11.tar.xz

wget -c https://www.kernel.org/pub/linux/kernel/projects/rt/3.18/patch-3.18.11-rt7.patch.gz

tar -xpf linux-3.18.11.tar.xz

gunzip patch-3.18.11-rt7.patch.gz

cp patch-3.18.11-rt7.patch linux-3.18.11

cd linux-3.18.11

cat patch-3.18.11-rt7.patch | patch -p1

make menuconfig

make

sudo make modules_install

sudo make install
