[cols="3*"]
|===
|link:developing.asciidoc[Back to Developing]
|link:../../index.asciidoc[Back to the main Documents index]
|link:../documentation-matrix.asciidoc[Documentation matrix]
|===
== [[packages-developing]]Setting up for development

. <<configure-apt,Configure the APT repository>>
. <<install-development-packages,Install development packages>>
. <<get-source-and-build,Get and build the source>>

== [[configure-apt]]Configure the APT repository

Make sure you have followed the instructions on configuring your APT-repo
and when you have done so return to here:

[cols="2*"]
|===
2+^|continue with (choose):
a|link:../getting-started/APT-packages-wheezy.asciidoc[Configure APT on Debian `wheezy`]

`i686`

`amd64`

`arm7 (Beaglebone)`

a|link:../getting-started/APT-packages-jessie.asciidoc[Configure APT on Debian `jessie`]

`i686`

`amd64`

`arm7 (Beaglebone)`

|===

== [[install-development-packages]]Install development packages

These instructions assume you have a pristine Debian installation, and you
have made sure you have `sudo` rights. Do not build Machinekit as root.

If you have previously installed the machinekit runtime packages, make sure
you have completely removed all of the runtime packages before you continue.


[source,bash]
----
sudo apt-get install libczmq-dev python-zmq libjansson-dev \
  libwebsockets-dev libxenomai-dev python-pyftpdlib cython bwidget
----

If you are on Debian Wheezy then you need to add wheezy-backports in the
package archive for cython 0.19:
[source,bash]
----
sudo sh -c \
  "echo 'deb http://ftp.us.debian.org/debian wheezy-backports main' > \
  /etc/apt/sources.list.d/wheezy-backports.list"
sudo apt-get update
sudo apt-get install -t wheezy-backports cython
----

== [[get-source-and-build]]Get and build the source

[source,bash]
----
sudo apt-get install git dpkg-dev
sudo apt-get install --no-install-recommends devscripts equivs
git clone https://github.com/machinekit/machinekit.git
cd machinekit
debian/configure -px
sudo mk-build-deps -ir
cd src
./autogen.sh
./configure
make
sudo make setuid
----

Add the next lines to your `.bashrc` file so that every new terminal is set up
correctly for running Machinekit.

[source,bash]
----
sh -c "echo 'if [ -f ~/machinekit/scripts/rip-environment ]; then\n\
    source ~/machinekit/scripts/rip-environment\n\
    echo \"Environment set up for running Machinekit and LinuxCNC\"\n\
fi\n' >> ~/.bashrc"
----

Users who wish to invoke machinekit (built with xenomai threads enabled) on a xenomai realtime kernel must ensure they are members of the xenomai group. If that wasn't already done when installing the kernel, then add each such user now

[source,bash]
----
sudo adduser <username> xenomai
----

[cols="3*"]
|===
|link:developing.asciidoc[Back to Developing]
|link:../../index.asciidoc[Back to the main Documents index]
|link:../documentation-matrix.asciidoc[Documentation matrix]
|===
