---
---
:skip-front-matter:

= gladevcp
:manmanual: HAL Components
:mansource: ../man/man9/gladevcp.asciidoc
:man version : 

== NAME
**gladevcp** - displays Virtual control Panels built with GTK / GLADE 

== SYNOPSIS
**loadusr gladevcp** __[-c componentname0x**N**] [-g WxH+Xoffset+Yoffset0x**N**] [-H halcmdfile] [-x windowid] gladefile.glade__

== DESCRIPTION
**gladevcp** parses a glade file and displays the widgets in a window.
Then calls **gladevcp**_makepins which again parses the gladefile looking for specific HAL widgets
then makes HAL pins and sets up updating for them. 

The HAL component name defaults to the basename of the glade file.

The -x option directs **gladevcp** to reparent itself under this X window id instead of creating its own toplevel window.

The -H option passes an input file for halcmd to be run after the **gladevcp** component is initialized. +
This is used in Axis when running **gladevcp** under a tab with the EMBED_TAB_NAME/EMBED_TAB_COMMAND ini file feature.

**gladevcp** supports gtkbuilder or libglade files though some widgets are not fully supported in gtkbuilder yet.

== ISSUES
For now system links need to be added in the glade library folders to point to our new widgets and catalog files. 

Look in lib/python/gladevcp/READ_ME for details

