= Machinekit Main Index
==============

As with all linux projects always read the link:machinekit-documentation/README.asciidoc[README] file first

Before asking questions on the google group Machinekit list,
please make sure you have read:

- link:machinekit-documentation/getting-help.asciidoc[Getting help]

== Navigating the documentation

=== Machinekit specific documentation

There is a matrix so it's easier to find part of the documentation that
is applicable to your project. This is at this moment very much a work
in progress.

- link:machinekit-documentation/documentation-matrix.asciidoc[Documentation matrix]

These documents are to be found in the */machinekit-documentation* directory
and will give a starting point for the various topic areas.
They link to legacy documentation and to new Machinekit documentation where it exists.

- link:machinekit-documentation/index-getting-started.asciidoc[Getting started manual]
- link:machinekit-documentation/index-user.asciidoc[User manual]
- link:machinekit-documentation/index-HAL.asciidoc[HAL manual]
- link:machinekit-documentation/index-integrator.asciidoc[Integrator manual]
- link:machinekit-documentation/index-developer.asciidoc[Developer manual]

=== Legacy documentation
A lot of the legacy Linuxcnc documentation is still valid, just mentally substitute Machinekit for Linuxcnc.

This is to be found in the */src* directory of this repo

Where appriate, links are made to it from Machinekit specific documents

=== Documenting
the Documenting manual is new and is at this time a working document about
the way the Machinekit project documenting is done.

- link:machinekit-documentation/documenting/documenting.asciidoc[Documenting manual]
