[cols="3*"]
|===
|link:getting-started-platform.asciidoc[Back to Getting Started]
|link:../../index.asciidoc[Back to the main Documents index]
|link:../documentation-matrix.asciidoc[Documentation matrix]
|===

Installing Packages
===================

Follow these steps to configure Apt and install a kernel and Machinekit packages:

[WARNING]
====
The kernel-naming convention used in these packages may change as
experience is accumulated, especially with ARM-based systems. Be sure to
check back here before installing a new kernel.
====

. *<<configure-apt,Configure Apt>>*
.. <<configure-APT-i686-amd64-arm7-wheezy,`wheezy` Configure Apt for i686, amd64 and arm7 (Beaglebone)>>
.. <<configure-APT-i686-amd64-arm7-jessie,`jessie` Configure Apt for i686, amd64 and arm7 (Beaglebone)>>
.. <<configure-APT-i686-arm6,Configure Apt for arm6 (Raspberry)>>
. [[install-kernels]]*<<install-RT-kernel,Install a realtime kernel>>*
.. <<rt-kernel-xenomai,Xenomai realtime kernel (all platforms)>>
.. <<rt-kernel-rt-preempt,RT-PREEMPT realtime kernel (i686 and amd64)>>
.. <<rt-kernel-rtai,RTAI realtime kernel (x86 and amd64)>>
. [[install-runtime-packs]]*<<install-runtime-packages,Install runtime packages>>*
. *<<post-installation,Post installation>>*



== [[configure-apt]]Configure Apt

[NOTE]
====
Different instructions exist for Debian Wheezy and Debian Jessie. Please choose
your installation.
====

=== [[configure-APT-i686-amd64-arm7-wheezy]]`wheezy` Configure Apt for i686, amd64 and arm7 (Beaglebone)


Copy and paste the following into a shell to configure the package archive:

[source,bash]
----
sudo sh -c \
  "echo 'deb http://deb.dovetail-automata.com wheezy main' > \
  /etc/apt/sources.list.d/machinekit.list; \
  apt-get update ; \
  apt-get install dovetail-automata-keyring"
sudo apt-get update
----
continue with:
[cols="1*"]
|===
|<<install-RT-kernel, install your kernel>>
|===

=== [[configure-APT-i686-amd64-arm7-jessie]]`jessie` Configure Apt for i686, amd64 and arm7 (Beaglebone)

==== Create APT `preferences` file and add `sid` repository
Because of the necessity of libczmq from the `sid` repository we need to
add a preferences file for APT to know that it should not use `sid` packages
*unless* it's been told to explicitly do so.

This instruction assumes there is no `preferences` file. If there is we assume
you know what you're doing and can adapt this info into your existing situation.

[source,bash]
----
sudo sh -c \
"echo 'Package: *
Pin: release a=stable
Pin-Priority: 900

Package: *
Pin: release o=Debian
Pin-Priority: -10' > \
/etc/apt/preferences;"
----

==== Add the `sid` repository to you debian sources list and update.

open as a root `/etc/apt/sources.list` and search for the following lines

[source,text]
----
deb http://ftp.nl.debian.org/debian/ jessie main
deb-src http://ftp.nl.debian.org/debian/ jessie main
----

If you use a different mirror, change appropriately
copy these lines and change `jessie` to `sid` which will look like (total)

[source,text]
----
deb http://ftp.nl.debian.org/debian/ jessie main
deb-src http://ftp.nl.debian.org/debian/ jessie main
deb http://ftp.nl.debian.org/debian/ sid main
deb-src http://ftp.nl.debian.org/debian/ sid main
----


==== Update your sources and install `libczmq` and `libczmq-dev`

[source,bash]
----
sudo apt-get update
sudo apt-get install -t sid libczmq libczmq-dev
----

==== Check correct version of libczmq-dev

[source,bash]
----
sudo apt-get install apt-show-versions
apt-show-versions | grep czmq
----

==== This should result in the following:

[source,bash]
----
me@debian:~$ apt-show-versions | grep czmq
libczmq-dev:amd64/sid 3.0.2-1 uptodate
libczmq3:amd64/sid 3.0.2-1 uptodate
----

==== Add Dovetail automata repository

[source,bash]
----
sudo sh -c \
  "echo 'deb http://deb.dovetail-automata.com jessie main' > \
  /etc/apt/sources.list.d/machinekit.list; \
  apt-get update ; \
  apt-get install dovetail-automata-keyring"
sudo apt-get update
----
continue with:
[cols="1*"]
|===
|<<install-RT-kernel, install your kernel>>
|===


=== [[configure-APT-i686-arm6]]Configure Apt for arm6 (Raspberry)

Copy and paste the following into a shell to configure the package
archive:
[source,bash]
----
sudo sh -c \
  "apt-key adv --keyserver hkp://keys.gnupg.net --recv-key 49550439; \
  echo 'deb http://0ptr.link/raspbian wheezy main' > \
  /etc/apt/sources.list.d/rpi-machinekit.list"
sudo apt-get update
----
continue with:
[cols="1*"]
|===
|<<install-RT-kernel, install your kernel>>
|===

== [[install-RT-kernel]]Install a realtime kernel

- <<rt-kernel-xenomai,Xenomai realtime kernel (all platforms)>>
- <<rt-kernel-rt-preempt,RT-PREEMPT realtime kernel (i686 and amd64)>>
- <<rt-kernel-rtai,RTAI realtime kernel (x86 and amd64)>>

=== [[rt-kernel-xenomai]]Xenomai realtime kernel (all platforms)

Choose and copy and paste the following into a shell to
install your kernel:
[source,bash]
----
sudo apt-get install linux-image-xenomai.x86-amd64 	  # amd64
----
[source,bash]
----
sudo apt-get install linux-image-xenomai.x86-686-pae      # i686
----
[source,bash]
----
sudo apt-get install linux-image-xenomai.beaglebone-omap  # beaglebone
----
[source,bash]
----
sudo apt-get install linux-image-xenomai                  # raspberry
----
[cols="2*"]
|===
2+^|continue with (choose):
| <<install-runtime-packages,install runtime packages>>
|link:../developing/machinekit-developing.asciidoc[install machinekit development packages]
|===

=== [[rt-kernel-rt-preempt]]RT-PREEMPT realtime kernel (i686 or amd64)

There is currently no stock Debian rt-preempt kernel for Jessie

You will need to build your own kernel

See link:../developing/building-rt-preempt-kernel.asciidoc[this document] for details.

The below instructions will work for Wheezy

Choose and copy and paste the following into a shell to
install your kernel:

[source,bash]
----
sudo apt-get install linux-image-rt-686-pae   # i686
----
[source,bash]
----
sudo apt-get install linux-image-rt-amd64     # amd64
----
[cols="2*"]
|===
2+^|continue with (choose):
| <<install-runtime-packages,install runtime packages>>
|link:../developing/machinekit-developing.asciidoc[install machinekit development packages]
|===

=== [[rt-kernel-rtai]]RTAI realtime kernel (x86 and amd64)

Choose and copy and paste the following into a shell to
install your kernel:

[source,bash]
----
sudo apt-get install linux-image-rtai.x86-686-pae # i686
----
[source,bash]
----
sudo apt-get install linux-image-rtai.x86-amd64   # amd64
----
[cols="2*"]
|===
2+^|continue with (choose):
| <<install-runtime-packages,install runtime packages>>
|link:../developing/machinekit-developing.asciidoc[install machinekit development packages]
|===

== [[install-runtime-packages]]Install runtime packages

For those wanting just Machinekit binaries, the following should
install the main 'machinekit' package for your kernel choice (multiple
kernels and flavors possible):

[source,bash]
----
sudo apt-get install machinekit-rt-preempt
----
[source,bash]
----
sudo apt-get install machinekit-xenomai
----
[source,bash]
----
sudo apt-get install machinekit-rtai-kernel
----
[source,bash]
----
sudo apt-get install machinekit-posix # non-RT (aka 'simulator mode')
----

== [[post-installation]]Post installation

Some platforms need additional steps/instructions. Please see below for
more information about specific platforms.

=== [[post-installation-raspberry]]Raspberry

The kernel image needs to be copied to the boot partition like so:
[source,bash]
----
sudo mv /boot/kernel.img /boot/kernel.img.bck
sudo cp /boot/vmlinuz* /boot/kernel.img
----

=== [[post-installation-beaglebone]]Beaglebone

Please see link:https://github.com/strahlex/asciidoc-sandbox/wiki/Creating-a-Machinekit-Debian-Image[Alex's installation hints]

[cols="3*"]
|===
|link:getting-started-platform.asciidoc[Back to Getting Started]
|link:../../index.asciidoc[Back to the main Documents index]
|link:../documentation-matrix.asciidoc[Documentation matrix]
|===
