
= [[configure-APT-i686-amd64-arm7-jessie]]Configure Apt for i686, amd64 and arm7 (Beaglebone, RPi2) for `jessie`

==== Create APT `preferences` file and add `sid` repository
Because of the necessity of `libczmq` and `libczmq-dev` from the `sid`
repository we need to add a preferences file for APT to know that it should not
use `sid` packages *unless* it's been told to explicitly do so.

This instruction assumes there is no `preferences` file. If there is we assume
you know what you're doing and can adapt this info into your existing situation.

[source,bash]
----
sudo sh -c \
"echo 'Package: *
Pin: release a=stable
Pin-Priority: 900

Package: *
Pin: release o=Debian
Pin-Priority: -10' > \
/etc/apt/preferences.d/sid;"
----

==== Add the `sid` repository to you debian sources list and update.

open as a root `/etc/apt/sources.list` and search for the following lines

[source,text]
----
deb http://ftp.nl.debian.org/debian/ jessie main
deb-src http://ftp.nl.debian.org/debian/ jessie main
----

If you use a different mirror, change appropriately
copy these lines and change `jessie` to `sid` which will look like (total)

[source,text]
----
deb http://ftp.nl.debian.org/debian/ jessie main
deb-src http://ftp.nl.debian.org/debian/ jessie main
deb http://ftp.nl.debian.org/debian/ sid main
deb-src http://ftp.nl.debian.org/debian/ sid main
----


==== Update your sources and install `libczmq` and `libczmq-dev`

[source,bash]
----
sudo apt-get update
sudo apt-get install -t sid libczmq-dev
----

==== Check correct version of libczmq-dev

[source,bash]
----
sudo apt-get install apt-show-versions
apt-show-versions | grep czmq
----

==== This should result in the following:

[source,bash]
----
me@debian:~$ apt-show-versions | grep czmq
libczmq-dev:amd64/sid 3.0.2-1 uptodate
libczmq3:amd64/sid 3.0.2-1 uptodate
----

==== Add Machinekit repository

[source,bash]
----
sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 43DDF224
sudo sh -c \
  "echo 'deb http://deb.machinekit.io/debian jessie main' > \
  /etc/apt/sources.list.d/machinekit.list"
sudo apt-get update
----
continue with:
[cols="2*"]
|===
|link:installing-packages.asciidoc#install-RT-kernel[install your RT kernel]
|link:../developing/machinekit-developing.asciidoc#install-development-packages[return to development setup]
|===
