---
---

:skip-front-matter:

= OLD and NEW Debian package repositories

Currently, the situation in Machinekit it such that there are two channels from which one can install Machinekit binaries. The newer version is using the https://cloudsmith.io/~machinekit/repos[Cloudsmith service] with repositories https://cloudsmith.io/~machinekit/repos/machinekit/packages/[Machinekit] (with dependency packages common to all other repositories), https://cloudsmith.io/~machinekit/repos/machinekit-hal/packages/[Machinekit-HAL] (with packages from the https://github.com/machinekit/machinekit-hal[Machinekit-HAL project]) and https://cloudsmith.io/~machinekit/repos/emcapplication/packages/[EMCApplication] (with packages from the https://github.com/machinekit/emcapplication[EMCApplication project]. You will need to have usually two or all three set up on you local machine to install Machinekit-HAL or EMCApplication.

To set up, you should follow instruction from Cloudsmith landing page of respective repository under _**S**et-**M**e-**U**p_ icon (here for example for https://cloudsmith.io/~machinekit/repos/machinekit-hal/setup/#formats-deb[Machinekit-HAL]):

[source,bash]
----
sudo apt install curl
curl -1sLf \
  'https://dl.cloudsmith.io/public/machinekit/machinekit-hal/cfg/setup/bash.deb.sh' \
  | sudo -E bash
----

Or if the automatic script is causing problems, use manual procedure:

[source,bash]
----
sudo apt-get install -y debian-keyring
sudo apt-get install -y debian-archive-keyring
sudo apt-get install -y apt-transport-https
curl -1sLf 'https://dl.cloudsmith.io/public/machinekit/machinekit-hal/cfg/gpg/gpg.D35981AB4276AC36.key' | sudo apt-key add -
curl -1sLf 'https://dl.cloudsmith.io/public/machinekit/machinekit-hal/cfg/setup/config.deb.txt?distro=$(lsb_release -is | tr "[:upper:]" "[:lower:]")\&codename=$(lsb_release -cs) | sudo tee -a /etc/apt/sources.list.d/machinekit-machinekit-hal.list'
apt-get update
----

This setup will allow you to install the currently maintained and developed Machinekit-HAL and EMCApplication packages.

For EMCApplication:

[source,bash]
----
sudo apt install emcapplication
----

For Machinekit-HAL (optionaly Machinekit-HAL-dev package):

[source,bash]
----
sudo apt install machinekit-hal
sudo apt install machinekit-hal-dev
----

For Machinekit-HAL meta-package which will install the *rt_preempt* real-time kernel:

[source,bash]
----
sudo apt install machinekit-hal-rt-preempt
----

Everything else in pages below (_Platforms_) which uses the `deb.machinekit.io` Debian repository address is related to the **old** distribution channel. This includes mainly the now deprecated https://github.com/machinekit/machinekit[Machinekit repository] and older Machinekit-HAL and Machinekit-CNC packages. This channel **will not get any updates in the future!** However, this version is stable and tested one.

You can get current *Preempt_RT* patched kernel packages from official Debian repositories. (Ubuntu unfortunately at this point does not offer this service.)

= Platforms


Follow these steps to configure Apt and install a kernel and Machinekit packages:

[NOTE]
1) The kernel-naming convention used in these packages may change as
experience is accumulated, especially with ARM-based systems. Be sure to
check back here before installing a new kernel.

[NOTE]
2)  Do NOT try to install more than one machinekit-{kernel-flavour} package on the same partition.
The packages now contain some kernel-flavour set files which used to be in the machinekit-dev
package and they conflict with each other. If you require to switch between different kernels on the same partition, build
a development RIP build and run from that.

:sectnums:

== EOL distributions ==

When a debian distribution becomes EOL it is not recommended to use
these packages. The Machinekit project will stop producing packages and
support for that distribution.

If you for whatever reason need to use these packages, please follow this
link to link:../unsupported-packages[the unsupported packages page].


== Debian Jessie on arm7 (BeagleBone)

:leveloffset: +2

- link:../APT-packages-jessie[APT Packages for Jessie]

- link:../install-rt-kernel-arm7[Install the kernel]

- link:../install-runtime-packages[Install Runtime Packages]

:leveloffset: -2

== Debian Jessie on arm7 (RPi2)

:leveloffset: +2

- link:../APT-packages-raspbian[APT Packages for Raspbian]

- link:../install-rt-kernel-RPi2[Install the kernel]

- link:../install-runtime-packages[Install Runtime Packages]

:leveloffset: -2

== Debian Jessie on i386

:leveloffset: +2

- link:../APT-packages-jessie[APT Packages for Jessie]

- link:../install-rt-kernel-i386[Install the kernel]

- link:../install-runtime-packages[Install Runtime Packages]

:leveloffset: -2

== Debian Jessie on amd64

:leveloffset: +2

- link:../APT-packages-jessie[APT Packages for Jessie]

- link:../install-rt-kernel-amd64[Install the kernel]

- link:../install-runtime-packages[Install Runtime Packages]

:leveloffset: -2


== Debian Stretch on armhf (BBB | RPi2/3 | Other armhf)

:leveloffset: +2

- link:../APT-packages-stretch[APT Packages for Stretch]

- link:../install-rt-kernel-armhf[Install the kernel]

- link:../install-runtime-packages[Install Runtime Packages]

:leveloffset: -2

== Debian Stretch on i386

:leveloffset: +2

- link:../APT-packages-stretch[APT Packages for Stretch]

- link:../install-rt-kernel-i386[Install the kernel]

- link:../install-runtime-packages[Install Runtime Packages]

:leveloffset: -2

== Debian Stretch on amd64

:leveloffset: +2

- link:../APT-packages-stretch[APT Packages for Stretch]

- link:../install-rt-kernel-amd64[Install the kernel]

- link:../install-runtime-packages[Install Runtime Packages]

:leveloffset: -2

== Debian Buster on armhf

:leveloffset: +2

- link:../APT-packages-buster[APT Packages for Buster]

- link:../install-rt-kernel-armhf[Install the kernel]

- link:../install-runtime-packages[Install Runtime Packages]

:leveloffset: -2

== Debian Buster on i386

:leveloffset: +2

- link:../APT-packages-buster[APT Packages for Buster]

- link:../install-rt-kernel-i386[Install the kernel]

- link:../install-runtime-packages[Install Runtime Packages]

:leveloffset: -2

== Debian Buster on amd64

:leveloffset: +2

- link:../APT-packages-buster[APT Packages for Buster]

- link:../install-rt-kernel-amd64[Install the kernel]

- link:../install-runtime-packages[Install Runtime Packages]

:leveloffset: -2


:sectnums!:
