---
---

:skip-front-matter:

= DEx(x) Debian link:https://github.com/machinekit/mksocfpga[ Mksocfpga ] Images

link:https://encrypted.google.com/search?q=Mksocfpga[What is Mksocfpga ]

There are pre-built (debian Stretch) sd-card images to get started with Machinekit on the
SocFPGA based DE0_Nano_SoC, DE10_Nano and the DE1_SoC boards from Terasic

- link:http://deb.machinekit.io/uploads/de10-nano/[Sd-card images are here]

All boards can run fine on both types of sd-card images, however if you want to use a display
the desktop image is setup to work out of the box with a hdmi 1920x1080 display (DE10_Nano only).
As long as you follow all the link:/docs/getting-started/u-boot-mksocfpga-altera-initial[DEx(x) Initial Setup Steps].

defaults: +
hostname:   mksocfpga-nano-soc +
user:       machinekit +
password:   machinekit +

- Instructions on writing a microSD card link:https://encrypted.google.com/search?q=Atlas-SoC+flashing+SD+card[can be found here] by doing a Google search. There are plenty examples and tutorials
around also for writing the image to the eMMC.

- On linux you can also use the bmap tool: +
Download image + bmap file and then insert sd-card and seek out the sd-card device name with:

[source,bash]
----
lsblk
----

be sure to pick the right dexice name (here it is /dev/sdx )
Copy to SD card:
[source,bash]
----
sudo bmaptool socfpga_stretch_machinekit_4.9.76-ltsi-rt-DExx_desktop_sd_2019-05-11.img.tar.bz2 /dev/sdx
----
