---
---
:skip-front-matter:

= axis-remote
:manmanual: HAL Components
:mansource: ../man/man1/axis-remote.1.asciidoc
:man version : 


== NAME


axis-remote -- AXIS Remote Interface


== SYNOPSIS


axis-remote __OPTIONS__|__FILENAME__


== DESCRIPTION


**axis-remote** is a small script that triggers commands in a running AXIS GUI.
Use **axis-remote --help** for further information.


== OPTIONS



**--ping**, **-p**
Check whether AXIS is running.

**--reload**, **-r**
Make AXIS reload the currently loaded file.

**--clear**, **-c**
Make AXIS clear the backplot.

**--quit**, **-q**
Make AXIS quit.

**--help**, **-h**, **-?**
Display a list of valid parameters for **axis-remote**.

**--mdi COMMAND**, **-m COMMAND**
Run the MDI command **COMMAND**.

**--run**, **-R**
Run the current loaded file.

**FILENAME**
Load the G-code file **FILENAME**.


== SEE ALSO
**axis**

Much more information about Machinekit and HAL is available in the Machinekit
and HAL User Manuals, found at /usr/share/doc/machinekit/.



== HISTORY


None
    


== BUGS


None known at this time. 



== AUTHOR


This man page was written by Alex Joni, for Linuxcnc and is now part of the Machinekit project. +
Amended by ArcEye <arceye@mgware.co.uk> with addition of **--run** capability


== REPORTING BUGS
Report bugs via the machinekit forum at https://groups.google.com/forum/#!forum/machinekit



== COPYRIGHT


Copyright (c) 2007 Alex Joni.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
