---
---
:skip-front-matter:

= AXIS
:manmanual: HAL Components
:mansource: ../man/man1/axis.asciidoc
:man version : 


== NAME
axis -- AXIS Machinekit Graphical User Interface


== SYNOPSIS
axis
__-ini__ __INIFILE__


== DESCRIPTION
**axis** is one of the Graphical User Interfaces (GUI) for Machinekit
It gets run by the runscript usually.


== OPTIONS

**INIFILE**
The ini file is the main piece of an Machinekit configuration. +
It is not the entire configuration; there are various other files that go with it
(NML files, HAL files, TBL files, VAR files). 

It is, however, the most important one, because it is the file that holds the configuration
together. 

It can adjust a lot of parameters itself, but it also tells
**Machinekit** which other files to load and use.

== ADDITIONAL INFO

The axis GUI exports several pins, which may be used to get its state and other uses.

**axisui.jog.x**  (OUT,bit)	+
TRUE if x axis is selected for jogging in the GUI

**axisui.jog.y**  (OUT,bit)	+
TRUE if y axis is selected for jogging in the GUI

**axisui.jog.z**  (OUT,bit)	+
TRUE if z axis is selected for jogging in the GUI

**axisui.jog.a**  (OUT,bit)	+
TRUE if a axis is selected for jogging in the GUI

**axisui.jog.b**  (OUT,bit)	+
TRUE if b axis is selected for jogging in the GUI

**axisui.jog.c**  (OUT,bit)	+
TRUE if c axis is selected for jogging in the GUI

**axisui.jog.u**  (OUT,bit)	+
TRUE if u axis is selected for jogging in the GUI

**axisui.jog.v**  (OUT,bit)	+
TRUE if v axis is selected for jogging in the GUI

**axisui.jog.w**  (OUT,bit)	+
TRUE if w axis is selected for jogging in the GUI

**axisui.jog.increment** (OUT,float) +
Current jog increment value set

**axisui.notifications-clear**       (IN,bit) +
**axisui.notifications-clear-info**  (IN,bit) +
**axisui.notifications-clear-error** (IN,bit) +
Clear the different sources of error messages with Axis without using GUI

**axisui.run-disable**               (IN,bit) +
A disable bit designed for college use or similar. +
All the functions such as touch off and jog will work, but a program cannot be started if it is TRUE.

Connect to safety door interlinks etc. to prevent un-guarded operation

== SEE ALSO

Description of and using the Axis GUI +
http://www.machinekit.io/docs/gui/axis/

== HISTORY



== BUGS
None known at this time. 


== AUTHOR
This man page written by Alex Joni, for LinuxCNC and is now part of the Machinekit project.


== REPORTING BUGS
Report bugs via the machinekit forum at https://groups.google.com/forum/#!forum/machinekit

== COPYRIGHT
Copyright (c) 2007 Alex Joni.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
