---
---
:skip-front-matter:

= AXIS
:manmanual: HAL Components
:mansource: ../man/man1/axis.asciidoc
:man version : 


== NAME
axis -- AXIS Machinekit Graphical User Interface


== SYNOPSIS
axis
__-ini__ __INIFILE__


== DESCRIPTION
**axis** is one of the Graphical User Interfaces (GUI) for Machinekit
It gets run by the runscript usually.


== OPTIONS

**INIFILE**
The ini file is the main piece of an Machinekit configuration. +
It is not the entire configuration; there are various other files that go with it
(NML files, HAL files, TBL files, VAR files). 

It is, however, the most important one, because it is the file that holds the configuration
together. 

It can adjust a lot of parameters itself, but it also tells
**Machinekit** which other files to load and use.



== SEE ALSO

Description of and using the Axis GUI +
http://www.machinekit.io/docs/gui/axis/

== HISTORY



== BUGS
None known at this time. 


== AUTHOR
This man page written by Alex Joni, for LinuxCNC and is now part of the Machinekit project.


== REPORTING BUGS
Report bugs via the machinekit forum at https://groups.google.com/forum/#!forum/machinekit

== COPYRIGHT
Copyright (c) 2007 Alex Joni.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
