---
---
:skip-front-matter:

= comp
:manmanual: HAL Components
:mansource: ../man/man1/comp.asciidoc
:man version : 


== NAME
comp -- Build, compile and install LinuxCNC HAL components


== SYNOPSIS

**comp** [**--compile**|**--preprocess**|**--document**|**--view-doc**] compfile...

__sudo__ **comp** [**--install**|**--install-doc**] compfile...

**comp** **--compile** **--userspace** cfile...

__sudo__ **comp** **--install** **--userspace** cfile...

__sudo__ **comp** **--install** **--userspace** pyfile...


== DESCRIPTION
**comp** performs many different functions:

Compile **.comp** and **.c** files into **.so** or **.ko** HAL realtime components (the **--compile** flag)

Compile **.comp** and **.c** files into HAL userspace components (the **--compile --userspace** flag)

Preprocess **.comp** files into **.c** files (the **--preprocess** flag)

Extract documentation from **.comp** files into **.9** manpage files (the **--document** flag)

Display documentation from **.comp** files onscreen (the **--view-doc** flag)

Compile and install **.comp** and **.c** files into the proper directory for HAL realtime components (the **--install** flag), which may require __sudo__ to write to system directories.

Install **.c** and **.py** files into the proper directory for HAL userspace components (the **--install --userspace** flag), which may require __sudo__ to write to system directories.

Extract documentation from **.comp** files into **.9** manpage files in the proper system directory (the **--install** flag), which may require __sudo__ to write to system directories.

Preprocess **.comp** files into **.c** files (the **--preprocess** flag)


== SEE ALSO

http://www.machinekit.io/docs/hal/comp/

http://www.machinekit.io/docs/man/man9/comp/ +
for documentation on the "two input comparator with hysteresis", a HAL realtime component with the same name as this program
