---
---
:skip-front-matter:

= HAL_INPUT
:manmanual: HAL Components
:mansource: ../man/man1/hal_input.1.asciidoc
:man version : 



== NAME
**hal_input** -- control HAL pins with any Linux input device, including USB HID devices


== SYNOPSIS
__loadusr__ **hal_input** __[-KRAL] inputspec ...__


== DESCRIPTION
hal_input is an interface between HAL and any Linux input device, including USB
HID devices. +
For each device named, **hal_input** creates pins corresponding
to its keys, absolute axes, and LEDs. +
At a fixed rate of approximately 10ms, it synchronizes the device and the HAL pins.


== INPUT SPECIFICATION
The __inputspec__ may be in one of several forms:

A string __S__

A substring or shell-style pattern match will be tested against the "name"of the device, +
the "phys" (which gives information about how it is connected), +
and the "id", which is a string of the form "Bus=... Vendor=... Product=... Version=...".  

You can view the name, phys, and id of attached devices by executing **less /proc/bus/input/devices**.  Examples:
[source, bash]
----
SpaceBall
"Vendor=001f Product=0001"
serio*/input0
----

A number __N__

This opens **/dev/input/event**__N__. +
Except for devices that are always attached to the system, this number may change over reboots or when the device is removed. +
For this reason, using an integer is not recommended.

When several devices are identified by the same string, add "**:**__N__" where
__N__ is the index of the desired device. 

For example, if **Mouse** matches **input3** and **input10**, then **Mouse** and **Mouse:0** +
select **input3**.  Specifying **mouse:1** selects input10.

For devices that appear as multiple entries in /dev/input, these indices are likely to stay the same every time.

For multiple identical devices, these indices are likely to depend on the insertion order, +
but stay the same across reboots as long as the devices are not moved to different ports or unplugged
while the machine is booted.

If the first character of the __inputspec__ is a "+", then **hal_input** requests exclusive access to the device. +
The first device matching an __inputspec__ is used.  Any number of __inputspec__s may be used.

A __subset option may preceed each inputspec__.  The subset option begins with a dash. +

Each letter in the subset option specifies a device feature to **include**.  Features that are not specified are excluded.

For instance, to export keyboard LEDs to HAL without exporting keys, use
[source, bash]
----
hal_input -L keyboard
----




== DEVICE FEATURES SUPPORTED

**EV_KEY** (buttons and keys).  __Subset -K__

**EV_ABS** (absolute analog inputs).  __Subset -A__

**EV_REL** (relative analog inputs).  __Subset -R__

**EV_LED** (LED outputs).  __Subset -L__


== HAL PINS AND PARAMETERS

=== For buttons

input.__N__**.btn-**__name__ bit out

input.__N__**.btn-**__name__**-not** bit out

Created for each button on the device.

=== For keys

input.__N__**.key-**__name__

input.__N__**.key-**__name__**-not**

Created for each key on the device.

=== For absolute axes

input.__N__**.abs-**__name__**-counts** s32 out

input.__N__**.abs-**__name__**-position** float out

input.__N__**.abs-**__name__**-scale** parameter float rw

input.__N__**.abs-**__name__**-offset** parameter float rw

input.__N__**.abs-**__name__**-fuzz** parameter s32 rw

input.__N__**.abs-**__name__**-flat** parameter s32 rw

input.__N__**.abs-**__name__**-min** parameter s32 r

input.__N__**.abs-**__name__**-max** parameter s32 r

Created for each absolute axis on the device.  

Device positions closer than **flat** to **offset** are reported as **offset** in **counts**, +
and **counts** does not change until the device position changes by at least **fuzz**.  

The position is computed as **position** = (**counts** - **offset**) / **scale**. +
The default value of **scale** and **offset** map the range of the axis reported by the operating system to [-1,1].  

The default values of **fuzz** and **flat** are those reported by the operating system. +
The values of **min** and **max** are those reported by the operating system.

=== For relative axes

input.__N__**.rel-**__name__**-counts** s32 out

input.__N__**.rel-**__name__**-position** float out

input.__N__**.rel-**__name__**-reset** bit in

input.__N__**.rel-**__name__**-scale** parameter float rw

input.__N__**.rel-**__name__**-absolute** parameter s32 rw

input.__N__**.rel-**__name__**-precision** parameter s32 rw

input.__N__**.rel-**__name__**-last** parameter s32 rw

Created for each relative axis on the device.  

As long as **reset** is true, **counts** is reset to zero regardless of any past or current axis movement.

Otherwise, **counts** increases or decreases according to the motion of the axis. +
**counts** is divided by position-scale to give **position**.

The default value of **position** is 1. +
There are some devices, notably scroll wheels, which return signed values with less resolution than 32 bits.

The default value of **precision** is 32.  **precision** can be set to 8
for a device that returns signed 8 bit values, or any other value from 1 to 32.

**absolute**, when set true, ignores duplicate events with the same value. +
This allows for devices that repeat events without any user action to work
correctly.  **last** shows the most recent count value returned by the
device, and is used in the implementation of **absolute**.

=== For LEDs

input.__N__**.led-**__name__ bit out

input.__N__**.led-**__name__**-invert** parameter bit rw

Created for each LED on the device.


== PERMISSIONS AND UDEV

By default, the input devices may not be accessible to regular
users +
**hal_input** requires read-write access, even if the device has no outputs.  

To change the default permission of a device, add a new file to /etc/udev/rules.d to set the device's GROUP to "plugdev".  

You can do this for all input devices with this rule:
[source, bash]
----
SUBSYSTEM=="input", MODE="0660", GROUP="plugdev"
----

You can also make more specific rules for particular devices. +
For instance, a SpaceBall input device uses the 'spaceball' kernel module, so a udev entry for
it would read:
[source, bash]
----
DRIVER=="spaceball", MODE="0660", GROUP="plugdev"
----

The next time the device is attached to the system, it will be accessible
to the "plugdev" group.

For USB devices, the udev line would refer to the device's Vendor and Product
values, such as 
[source, bash]
----
SYSFS{idProduct}=="c00e", SYSFS{idVendor}=="046d", MODE="0660", GROUP="plugdev"
----
for a particular logictech-brand mouse.

For more information on writing udev rules, see **udev(8)**.


== BUGS

The initial state of keys, buttons, and absolute axes are erroneously reported
as FALSE or 0 until an event is received for that key, button, or axis.


== SEE ALSO

**udev(8)**
