---
---
:skip-front-matter:

= HALTCL
:manmanual: HAL Components
:mansource: ../man/man1/haltcl.asciidoc
:man version:


== NAME
**haltcl** -- manipulate the LinuxCNC HAL from the command line using a tcl
interpeter.



== SYNOPSIS
**haltcl** [__-i inifile__] [__filename__]



== DESCRIPTION
**haltcl** is used to manipulate the HAL (Hardware Abstraction
Layer) from the command line using a tcl interpreter. +

**haltcl** can optionally read commands from a file (filename), allowing
complex HAL configurations to be set up with a single command.



== OPTIONS

**-i** __inifile__ +
If specified, the inifile is read and used to create tcl global variable
arrays.  An array is created for each SECTION of the inifile with
elements for each ITEM in the section.
[source, bash]
----
For example, if the inifile contains:
[SECTION_A]ITEM_1 =  1
[SECTION_A]ITEM_2 =  2
[SECTION_B]ITEM_1 =  1

The corresponding tcl variables are:
SECTION_A(ITEM_1) =  1
SECTION_A(ITEM_2) =  2
SECTION_B(ITEM_1) =  1
----

**-ini** __inifile__ -- declining usage, use **-i** __inifile__ +

**filename** +
If specified, the tcl commands of **filename** are executed.  If no filename
is specified, **haltcl** opens an interactive session.



== COMMANDS
**haltcl** includes the commands of a tcl interpreter augmented with
commands for the hal language as described for **halcmd**. +
The augmented commands can be listed with the command:

[source, bash]
----
haltcl: hal --commands

addf alias delf delsig getp gets ptype stype help linkpp linkps linksp list loadrt loadusr lock net newsig save setexact_for_test_suite_only setp sets show source start status stop unalias unlinkp unload unloadrt unloadusr unlock waitusr
----

Two of the augmented commands, `list` and `gets`, require special treatment to
avoid conflict with tcl built-in commands having the same names.  To use these
commands, precede them with the keyword `hal`:

[source, bash]
----
   hal list
   hal gets
----


== REPORTING BUGS
Report bugs to the Machinekit forum +
https://groups.google.com/forum/#!forum/machinekit

== COPYRIGHT
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.



== SEE ALSO
**halcmd**, **halrun**
