---
---
:skip-front-matter:

= hal_export_funct
:manmanual: HAL Components
:mansource: ../man/man3/hal_export_funct.asciidoc
:man version : 


== NAME

**hal_export_funct** -- create a realtime function callable from a thread



== SYNTAX
**typedef void** **( *hal_funct_t )** ( **void** *__arg__, **long** __period__ )

**int hal_export_funct** ( **const char** *__name__, **hal_funct_t** __funct__, **void** *__arg__, **int** __uses_fp__, **int** __reentrant__, **int** __comp_id__)



== ARGUMENTS
__name__ +
The name of the function.

__funct__ +
The pointer to the function

__arg__ +
The argument to be passed as the first parameter of __funct__

__uses_fp__ +
Nonzero if the function uses floating-point operations, including assignment
of floating point values with "=".

__reentrant__ +
If reentrant is non-zero, the function may be preempted and called again
before the first call completes.  +
Otherwise, it may only be added to one
thread.

__comp_id__ +
A HAL component identifier returned by an earlier call to **hal_init**.



== DESCRIPTION
**hal_export_funct** makes a realtime function provided by a component
available to the system.  +
A subsequent call to **hal_add_funct_to_thread**
can be used to schedule the execution of the function as needed by the system.

When this function is placed on a HAL thread, and HAL threads are started,
__funct__ is called repeatedly with two arguments: +
__void *arg__ is the
same value that was given to **hal_export_funct**, +
and __long period__ is
the interval between calls in nanoseconds.

Each call to the function should do a small amount of work and return.



== RETURN VALUE
Returns a HAL status code.



== SEE ALSO
**hal_create_thread** +
**hal_add_funct_to_thread**
