---
---
:skip-front-matter:

= hm2_uart_send

:manmanual: HAL Components
:mansource: ../man/man3/hm2_uart_send.asciidoc
:man version : 

== NAME
**hm2_uart_send** -- write data to a Hostmot2 UART



== SYNTAX
**int hm2_uart_send** ( **char** *__name__,  **unsigned char** __data[]__, **int** __count__ )



== DESCRIPTION
**hm2_uart_send** write 'count' bytes of data to the UART "name" from the 
buffer 'data'. 

The UART FIFO is 64 bytes deep, attempts to transmit more than 64 bytes may have
unexpected effects. 

"name" is a unique string given to each UART during hostmot2 setup. +
The names of 
the available channels are printed to standard output during the driver loading 
process and take the form: +
**hm2_**__<board name>.<board index>__.**uart**.__<index>__ +
For example +
**hm2_5i23.0.uart.0**

This function performs writes of data to the specified UART.It should be used 
inside a function in a realtime or userspace HAL component.



== RETURN VALUE
Returns the number of bytes sent on success and -1 on failure.

== LICENCE
Issued under the terms of the GPL v2 License or any later version

== AUTHOR
Andy Pugh

== SEE ALSO
**hm2_uart_setup** +
**hm2_uart_read**

See link:https://github.com/machinekit/machinekit/blob/master/src/hal/drivers/mesa_uart.comp[mesa_uart.comp] for an example usage
