---
layout: docs
---
:imagesoutdir: docs/documenting/diagram-examples


:toc:

== How to created embedded diagrams for this website

Besides inserting your locally created images, the
link:https://github.com/mhaberler/docker-jekyll-asciidoctor/tree/master/jekyll-asciidoctor-base[formatting engine]
used for the machinekit website supports a variety of embedded diagram types:
Diagrams can be created by embedded markup and will be rendered to images in the website automatically.

See the link:https://github.com/asciidoctor/asciidoctor-diagram[Asciidoctor Diagram manual] for details.

=== ditaa - DIagrams Through Ascii Art

See the link:http://ditaa.sourceforge.net/[ditaa website] for details.

[ditaa, "ditaa-test"]
----
                   +-------------+
                   | asciidoctor |-------+
                   |  diagram    |       |
                   +-------------+       | png out
                       ^                 |
                       | ditaa in        |
                       |                 v
 +--------+   +--------+----+    /---------------\
 |        | --+ asciidoctor +--> |               |
 |  Text  |   +-------------+    |Beatiful output|
 |Document|   |   !magic!   |    |               |
 |     {d}|   |             |    |               |
 +---+----+   +-------------+    \---------------/
     :                                   ^
     |          Lots of work             |
     +-----------------------------------+
----

=== shaape -  Ascii drawings

See the link:https://github.com/christiangoltz/shaape[shaape manual].

[shaape, "shaape-example5", "svg", width=80%]
----
      ^  ^  b  a   v           |        in>---+-----+-----> out1
      |  |  |  |   |           +              |     |
   >--[--[--|--|---|          /|\             |     *----->'out 2'
      |  |  |  |   |lower    +'c'+            |
      +--+--(--(---|         |   |            |    +------>'3'
            |  |   |        'd' 'e'           |   /
            |  +---~--->                      +--+-------->'v'    
            |      |                 
            +------~--->
                   |
                   v
                                                              
 +-->->->->-+        +---------------------------------------+                                                         
 |          |        | +------------+ stacked +------------+ |                 
 ^ arrowbox v        | | inner1     |         | inner2     | |                 
 |          | +--+   | | +-------++ +--**     | +--------+ | |                  
 ^          v |  |   | | |inner3  | |    **-->+ |inner4  | | |                  
 |          | *  |   | | |        | |         | |        | | |                  
 +--<-<-<-<-+ *  *   | | |        +-------------+        | | |                 
              *  *   | | +--------+ |         | +--------+ | | 
        +--***   *   | +------------+         +------------+ |                         
        | flat   *   +---------------------------------------+              
        +----****                                                                      
   /\               *********               +-----+     +-----+       
  /  \    +------+ + top     +   ********   |     |\    +--+--+                                
 /flat\  /      /  |*********|  * shape3 *  |     +-+   +--+--+                     
 \    / /shape1/   | shape2  |  *        *  |overlap|                                       
  \  / +------+    +         +   ********   +-------+                    
   \/               *********                                       
options:
- ".*": {fill:[[0.6, 0.8, 0.8], flat], frame:[[0.2, 0.5, 0.4, 1], solid, 2], text:[[0.1, 0.3, 0.2]]}
- "_line_": {fill:[[0.1, 0.1, 0.1], solid, 2]}
- "(flat)|(top)": {fill:[[0.1, 0.1, 0.1, 1], no-shadow, flat], frame:[[0.3, 0.8, 0], dotted, 3], text:[[0.9, 0.9, 0.9]]}
- "arrowbox": {fill:[[0.7, 0.7, 0, 0.5], no-shadow, flat], frame:[[0.3, 0.8, 0], dashed, 3], text:[[0, 0, 0]]}
- "shape[0-9]": {fill:[[0.2, 0.2, 0.2], gradient], frame:[[0.1, 0.5, 0], dotted, 3]}
- "stacked": {fill:[[0.15, 0.3, 0.3], flat], text:[[0, 0, 0]]}
- "inner[34]": {frame:[[0, 0, 0], 1, dotted], text:[[0, 0, 0]]}
- "inner[12]": {fill:[[0.3, 0.6, 0.6], flat], frame:[[0, 0, 0], dashed, 1], text:[[0, 0, 0,]]}
- "a": {fill:[[0.5, 0.0, 0.0, 0.5], 4]}
- "b": {fill:[[0.5, 0.0, 0.5, 0.5], 4]}
- "lower": {fill:[[0.0, 0.5, 0.0, 0.5], 4]}
- "_arrow_": {fill:[[0.5, 0.0, 0.0, 1], flat]}

----


=== Graphviz - Graph Visualization Software

See the link:http://www.graphviz.org/content/dot-language[Graphviz website].

["graphviz", "graphviz_example", "svg"]
---------------------------------------------------------------------
digraph automata_0 {
  size ="8.5, 11";
  node [shape = circle];
  0 [ style = filled, color=lightgrey ];
  2 [ shape = doublecircle ];
  0 -> 2 [ label = "a " ];
  0 -> 1 [ label = "other " ];
  1 -> 2 [ label = "a " ];
  1 -> 1 [ label = "other " ];
  2 -> 2 [ label = "a " ];
  2 -> 1 [ label = "other " ];
  "Machine: a" [ shape = plaintext ];
}
---------------------------------------------------------------------

=== blockdiag -  block diagrams

See the http://blockdiag.com/en/blockdiag[blockdiag manual].

[blockdiag, "blockdiag_example", "svg", width=90%]
----
blockdiag {
   A -> B -> C -> D;
   A -> E -> F -> G;
}
----

=== actdiag - activity diagrams

See the link:http://blockdiag.com/en/actdiag/index.html[actdiag manual].

[actdiag, "actdiag_example", "svg"]
----
actdiag {
  write -> convert -> image

  lane user {
     label = "User"
     write [label = "Writing reST"];
     image [label = "Get diagram IMAGE"];
  }
  lane actdiag {
     convert [label = "Convert reST to Image"];
  }
}
----

=== nwdiag - network diagrams

See the link:http://blockdiag.com/en/nwdiag/index.html[nwdiag manual].

[nwdiag, "nwdiag_example", "svg", width=90%]
----
nwdiag {
  network dmz {
      address = "210.x.x.x/24"

      web01 [address = "210.x.x.1"];
      web02 [address = "210.x.x.2"];
  }
  network internal {
      address = "172.x.x.x/24";

      web01 [address = "172.x.x.1"];
      web02 [address = "172.x.x.2"];
      db01;
      db02;
  }
}
----

=== seqdiag - sequence diagrams

See the link:http://blockdiag.com/en/seqdiag/index.html[seqdiag manual].

[seqdiag, "seqdiag_example", "svg"]
----
seqdiag {
  // normal edge and doted edge
  A -> B [diagonal, label = "normal edge"];
  B --> C [label = "dotted edge"];

  B <-- C [label = "return dotted edge"];
  A <- B [label = "return edge"];

  // asynchronus edge
  A ->> B [label = "asynchronus edge"];
  B -->> C [label = "asynchronus dotted edge"];

  B <<-- C [label = "return asynchronus doted edge"];
  A <<- B [label = "return asynchronus edge"];

  // self referenced edge
  A -> A [label = "self reference edge"];
}
----

=== mermaid - sequence diagrams and flowchars

See the link:http://knsv.github.io/mermaid/[mermaid website].

These come out too wide, for some reason this plugin
does not respect the link:https://github.com/asciidoctor/asciidoctor-pdf/issues/76[width= parameter discussed here].

[mermaid, "mermaid_seqdiag_example", "svg"]
----
%% Sequence diagram code
sequenceDiagram
    Alice ->> Bob: Hello Bob, how are you?
    Bob-->>John: How about you John?
    Bob--x Alice: I am good thanks!
    Bob-x John: I am good thanks!
    Note right of John: Bob thinks a long<br/>long time, so long<br/>that the text does<br/>not fit on a row.

    Bob-->Alice: Checking with John...
    Alice->John: Yes... John, how are you?
----

[mermaid, "mermaid_flowchart_example", "svg"]
----
graph LR
    A[Square Rect] -- Link text --> B((Circle))
    A --> C(Round Rect)
    B --> D{Rhombus}
    C --> D
----


=== wavedrom - Digital Timing Diagrams

See the link:http://wavedrom.com/[wavedrom website].

["wavedrom",  "svg"]
---------------------------------------------------------------------
{ signal: [
  {    name: 'clk',   wave: 'p..Pp..P'},
  ['Master',
    ['ctrl',
      {name: 'write', wave: '01.0....'},
      {name: 'read',  wave: '0...1..0'}
    ],
    {  name: 'addr',  wave: 'x3.x4..x', data: 'A1 A2'},
    {  name: 'wdata', wave: 'x3.x....', data: 'D1'   },
  ],
  {},
  ['Slave',
    ['ctrl',
      {name: 'ack',   wave: 'x01x0.1x'},
    ],
    {  name: 'rdata', wave: 'x.....4x', data: 'Q2'},
  ]
]}
---------------------------------------------------------------------


=== pygments - highlighting sourcecode

See the link:http://pygments.org[pygments website] .

Default hightlighing style is {pygments-css} using {source-highlighter} as highlighting engine.
These link:https://github.com/jwarby/jekyll-pygments-themes[css themes] are available.

Hightlighting for HAL and G-Code: contributors welcome!

A bit of Python:

[source,python]
----
def foo(bar):
    pass    # a comment
----

Ini files:
[source,ini]
----
# Hardware Abstraction Layer section 
[HAL]

# The run script first uses halcmd to execute any HALFILE
# files, and then to execute any individual HALCMD commands.
#

# list of hal config files to run through halcmd
# files are executed in the order in which they appear
HALFILE = core_sim.hal
HALFILE = sim_spindle_encoder.hal
HALFILE = axis_manualtoolchange.hal
HALFILE = simulated_home.hal

----

